controller_list:
  - name: fake_left_controller
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
  - name: fake_right_controller
    joints:
      - right_joint_s
      - right_joint_l
      - right_joint_e
      - right_joint_u
      - right_joint_r
      - right_joint_b
      - right_joint_t
  - name: fake_dual_controller
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
      - right_joint_s
      - right_joint_l
      - right_joint_e
      - right_joint_u
      - right_joint_r
      - right_joint_b
      - right_joint_t