 1 <xacro:macro name="leg" params="prefix reflect">
   2     <link name="${prefix}_leg">
   3         <visual>
   4             <geometry>
   5                 <box size="${leglen} 0.1 0.2"/>
   6             </geometry>
   7             <origin xyz="0 0 -${leglen/2}" rpy="0 ${pi/2} 0"/>
   8             <material name="white"/>
   9         </visual>
  10         <collision>
  11             <geometry>
  12                 <box size="${leglen} 0.1 0.2"/>
  13             </geometry>
  14             <origin xyz="0 0 -${leglen/2}" rpy="0 ${pi/2} 0"/>
  15         </collision>
  16         <xacro:default_inertial mass="10"/>
  17     </link>
  18 
  19     <joint name="base_to_${prefix}_leg" type="fixed">
  20         <parent link="base_link"/>
  21         <child link="${prefix}_leg"/>
  22         <origin xyz="0 ${reflect*(width+.02)} 0.25" />
  23     </joint>
  24     <!-- A bunch of stuff cut -->
  25 </xacro:macro>
